### ISSUE TITLE
ZWJ missing

### ISSUE THREAD

**Issue by befranz** [jakewarren/punycoder#1]
Punycodes/Emojis containing Zero Width Joiner are not handled the right way. 

xn--8k8hlfr9n should be 🧑🏾‍🎨 not 🧑🏾🎨

punycoder 🧑🏾‍🎨 shows xn--1ug6825plhas9r instead of xn--8k8hlfr9n

Any chance to fix this? Besides that I like punycoder!

**Comment by jakewarren** [comment]
Hi @befranz, thanks for the report! This program is pretty much just a stub to use the Go standard library (golang.org/x/net/idna) so you will have to create an issue [upstream](https://github.com/golang/go/issues). 

I ran your test cases against a few online conversion tools and I am not able to replicate. Perhaps support is just not widely available yet for zero width joiners? Sorry, I don't really know enough about it to help. 
- https://gchq.github.io/CyberChef/#recipe=From_Punycode(true)&input=eG4tLThrOGhsZnI5bg
- https://www.punycoder.com/
- https://dnschecker.org/idn-punycode-converter.php
- https://www.charset.org/punycode?encoded=xn--8k8hlfr9n&decode=Punycode+to+normal+text

**Comment by befranz** [comment]
Thank you for your quick response! Yeah, obviously most of punycode code is not ready for it yet, I'll raise an issue at the link you provided.

A site which already supports ZWJ: https://www.niami.io/domain/xn--8k8hlfr9n
